# For use with conda to create a new environment for the AI Base project.
name: aibase
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.10
  - pip=25.0.1
  - pip:
    - datasets
    - gradio
    - huggingface_hub
    - jupyterlab
    - keras
    - langchain
    - langchain-anthropic
    - langchain-huggingface
    - langchain-mistralai
    - langchain-ollama
    - langchain-openai
    - langgraph
    - matplotlib
    - numpy
    - pandas
    - pipdeptree
    - polars
    - scikit-learn
    - scipy
    - seaborn
    - tensorflow
    - tf_keras
    - torch
    - transformers