version: '3'

tasks:
  build:
    desc: Build the Docker image
    cmds:
      - docker build -t aibase .

  shell:
    desc: Run bash in the Docker container with current directory mounted
    cmds:
      - docker run -it --rm --env-file .env -v ${PWD}:/app aibase bash