version: '3'

tasks:
  build:
    desc: Build the Docker image
    cmds:
      - docker build -t aibase .

  shell:
    desc: Run bash in the Docker container with current directory mounted
    cmds:
      - docker run -it --rm --env-file .env -v ${PWD}:/app aibase bash
   
  # jupyter:
  #  desc: Run Jupyter in the Docker container
  #  cmds:
      # - docker run -p 8888:8888 --rm --env-file .env -v ${PWD}:/app aibase jupyter lab -ip=0.0.0.0 --allow-root 
      # - docker run --rm aibase 